export const actions = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SET_CART: "SET_CART",
  SET_PRODUCT: "SET_PRODUCT",
  SET_TOTAL_PRODUCT_PRICE: "SET_TOTAL_PRODUCT_PRICE",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  INCREMENT_ITEM_QUANTITY: "INCREMENT_ITEM_QUANTITY",
  DECREMENT_ITEM_QUANTITY: "DECREMENT_ITEM_QUANTITY",
};
